#!/bin/sh
DAEMON=/usr/bin/aesdsocket

case "$1" in
  start)
    echo "Starting aesdsocket"
    start-stop-daemon -S -x ${DAEMON} -- -d
    ;;
  stop)
    echo "Stopping aesdsocket"
    start-stop-daemon -K -x ${DAEMON} -s TERM
    ;;
  restart)
    "$0" stop
    sleep 1
    "$0" start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
exit 0
